import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "revalidate-bug",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta http-equiv="refresh" content="1" />
      </head>
      <body>{children}</body>
    </html>
  );
}
